name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     #  Étape 1 : Clonage du repository
      - name: Checkout repository
        uses: actions/checkout@v4

       #Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
     # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Construction et publication des images Docker
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./back  # Chemin vers le répertoire contenant le Dockerfile pour le backend
          file: ./back/Dockerfile 
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/myapp-backend:latest
