name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Étape 2 : Configuration Java 
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Étape 3 : Compilation du projet avec Maven
      - name: Build with Maven
        run: mvn clean install
        working-directory: back
        

      # Étape 4 : Lancement analyse SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args:
            -Dprojet.settings=sonar-project.properties
          # args: >
          #   -Dsonar.projectKey=Migueranda_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD_5f302f1c-87c0-48b5-923a-f58c9c4cb441
          #   -Dsonar.sources=back/src/main/java,front/src/app
          #   -Dsonar.java.binaries=back/target/classes
          #   -Dsonar.java.coveragePlugin=jacoco
          # -Dsonar.jacoco.reportPaths=target/jacoco-report/jacoco.xml
