name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactiver les shallow clones pour une meilleure analyse

      # Étape 2 : Configurer Java (assurer la compatibilité avec votre projet)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Étape 3 : Compiler le projet avec Maven
      - name: Build with Maven
        run: mvn clean install
        # Si ton projet est dans un sous-répertoire, tu peux spécifier le chemin avec 'working-directory'

      # Étape 4 : Lancer l'analyse SonarQube
      - uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Étape optionnelle : Vérifier si la Quality Gate est passée
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
