name: Angular Front-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' 
      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install
        working-directory: front  

      # Étape 4 : Exécuter les tests Angular avec Karma
      - name: Run Angular tests with Karma
        run: npm run test -- --watch=false --code-coverage
        working-directory: front
        
      # Étape 5 : Sauvegarder les rapports de couverture comme artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: front/coverage 
