name: Frontend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #  Étape 1 : Clonage du repository
      - name: Checkout repository
        uses: actions/checkout@v4

    #Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    # Construction et publication des images Docker
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
        # Tags des images Docker  
          tags: ${{ vars.DOCKERHUB_USERNAME }}/myapp-frontend:latest
