jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configuration Java
      - name: Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'

      # Étape 3 : Installation des dépendances et exécution des tests
      - name: Run Maven tests and JaCoCo
        run: mvn clean verify
        working-directory: back
        java-version: '17'

      - name: Build and run tests with Maven
        run: mvn clean verify 
        working-directory: back

      # Étape : Sauvegarde des rapports de tests unitaires Surefire
      - name: Upload Surefire test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: back/target/jacoco-report/jacoco.xml

      # Étape : Lancer l'analyse SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=Migueranda_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD_5f302f1c-87c0-48b5-923a-f58c9c4cb441
            -Dsonar.sources=back/src/main/java
            -Dsonar.tests=back/src/test/java
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.jacoco.reportPaths=back/target/jacoco-report/jacoco.xml   