name: Spring Boot CI with JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configurer Java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Étape 3 : Installer les dépendances et exécuter les tests dans le répertoire 'back'
      - name: Run Maven tests and JaCoCo
        run: mvn clean verify
        working-directory: back

      # Étape 4 : Sauvegarder les rapports JaCoCo comme artifact
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco





   
    
