name: Spring Boot CI with JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configurer Java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Ou '11' selon votre projet
          distribution: 'temurin'

      # Étape 3 : Se déplacer dans le répertoire 'back' qui contient le fichier pom.xml
      - name: Change directory to the backend folder
        working-directory: back

      # Étape 4 : Installer les dépendances et exécuter les tests
      - name: Run Maven tests and JaCoCo
        run: mvn clean verify

      # Étape 5 : Sauvegarder les rapports JaCoCo comme artifact
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: back/target/site/jacoco




   
    
