jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests with Maven
        run: mvn clean verify  # e génère les rapports JaCoCo et Surefire

      # Étape : Sauvegarder les rapports de tests unitaires Surefire
      - name: Upload Surefire test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: back/target/surefire-reports  # Chemin des rapports de tests unitaires

      # Étape : Lancer l'analyse SonarQube
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
